vich_uploader:
    db_driver: orm

    mappings:
        post_image:
            uri_prefix:         '%brt_blog_uri_prefix%'
            upload_destination: '%kernel.root_dir%/../web/images/posts'
            namer:              vich_uploader.namer_uniqid