brt_blog_adminpage:
    resource: "@BRTBlogBundle/Controller/AdminController.php"
    type:     annotation

brt_blog_post:
    resource: "@BRTBlogBundle/Controller/AdminEntriesController.php"
    type:     annotation

brt_blog_default:
    resource: "@BRTBlogBundle/Controller/DefaultController.php"
    type: annotation

brt_blog_blog:
    resource: "@BRTBlogBundle/Controller/BlogController.php"
    type: annotation
