<?php

namespace BRT\BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLastPosts($limit = 10){

        $dql = " SELECT post FROM BRTBlogBundle:Post post ORDER BY post.created DESC";
        $query = $this->_em->createQuery($dql);
        $query->setFirstResult(0);
        $query->setMaxResults($limit);
        return $query->getResult();

    }
}
